import streamlit as st
import pandas as pd
import json
import os
import sys
from datetime import datetime

sys.path.append(os.path.join(os.path.dirname(__file__), "src"))

from analyze import get_summary
from visualize import (
    plot_sales_by_region,
    plot_profit_by_category,
    plot_monthly_trend,
    plot_top_products,
)
from generate_report import generate_report

st.set_page_config(page_title="AI BI Report Generator", layout="wide")

st.title("Automated BI Report Generator")
st.write("Upload a sales CSV file and get a complete business intelligence report with charts, generated by AI.")

uploaded_file = st.file_uploader("Upload your sales CSV", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file, encoding="latin1")

    required_cols = ["Order Date", "Region", "Category", "Sub-Category", "Product Name", "Sales", "Profit", "Quantity", "Discount", "Segment", "Order ID"]
    missing = [c for c in required_cols if c not in df.columns]

    if missing:
        st.error(f"Missing required columns: {missing}")
    else:
        df["Order Date"] = pd.to_datetime(df["Order Date"])

        st.subheader("Data Preview")
        st.dataframe(df.head(10))

        if st.button("Generate Report"):
            with st.spinner("Analyzing data..."):
                summary = get_summary(df)

            os.makedirs("reports/charts", exist_ok=True)

            with st.spinner("Generating charts..."):
                plot_sales_by_region(df, "reports/charts")
                plot_profit_by_category(df, "reports/charts")
                plot_monthly_trend(df, "reports/charts")
                plot_top_products(df, "reports/charts")

            st.subheader("Key Metrics")
            col1, col2, col3, col4 = st.columns(4)
            col1.metric("Total Sales", f"${summary['total_sales']:,.0f}")
            col2.metric("Total Profit", f"${summary['total_profit']:,.0f}")
            col3.metric("Profit Margin", f"{summary['profit_margin_pct']}%")
            col4.metric("Total Orders", summary['total_orders'])

            st.subheader("Charts")
            c1, c2 = st.columns(2)
            c1.image("reports/charts/sales_by_region.png")
            c2.image("reports/charts/profit_by_category.png")
            c1.image("reports/charts/monthly_sales_trend.png")
            c2.image("reports/charts/top_products.png")

            with st.spinner("Generating AI report... this may take a moment"):
                report_text = generate_report(summary)

            st.subheader("AI-Generated Business Report")
            st.markdown(report_text)

            st.download_button(
                label="Download Report as Markdown",
                data=report_text,
                file_name=f"bi_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md",
                mime="text/markdown"
            )
else:
    st.info("Upload a CSV file to get started. The file should follow the Superstore dataset structure (Order Date, Region, Category, Sales, Profit, etc).")